NetflixApp/Models/Serie.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace NetflixApp.Models
{
    public class Serie
    {
        public int ID { get; set; }
        public string Title { get; set; }

        [Display( Name = "Release Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime ReleaseDate { get; set; }

        public string Genre { get; set; }
        public int Seasons { get; set; }
        public string Rating { get; set; }
    }
}

NetflixApp/Controllers/SerieController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NetflixApp.Models;

namespace NetflixApp.Controllers
{
    public class SerieController : Controller
    {
        private NetflixDbContext db = new NetflixDbContext();

        // GET: Serie
        public ActionResult Index(string searchString, string serieGenre) 
        {
            var GenreList = new List<string>();
            //Bring Serie Genre from DB
            var genres = from g in db.Series
                         orderby g.Genre
                         select g.Genre;
            //Distinct only Genres
            GenreList.AddRange(genres.Distinct());

            //Pass the Genre List to a SelectList for the View using ViewBag
            ViewBag.serieGenre = new SelectList(GenreList);

            // Bring series from DB
            var series = from s in db.Series
                         select s;

            if(!String.IsNullOrEmpty(searchString))
            {
                // Limit series based on searchString
                series = series.Where(s => s.Title.Contains(searchString));
            }

            if(!String.IsNullOrEmpty(serieGenre))
            {
                //Limit Series based on serieGenre
                series = series.Where(s => s.Genre == serieGenre);
            }

            // return new list of series
            return View(series);
        }

        // GET: Serie/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Serie serie = db.Series.Find(id);
            if (serie == null)
            {
                return HttpNotFound();
            }
            return View(serie);
        }

        // GET: Serie/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Serie/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Title,ReleaseDate,Genre,Seasons,Rating")] Serie serie)
        {
            if (ModelState.IsValid)
            {
                db.Series.Add(serie);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(serie);
        }

        // GET: Serie/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Serie serie = db.Series.Find(id);
            if (serie == null)
            {
                return HttpNotFound();
            }
            return View(serie);
        }

        // POST: Serie/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Title,ReleaseDate,Genre,Seasons,Rating")] Serie serie)
        {
            if (ModelState.IsValid)
            {
                db.Entry(serie).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(serie);
        }

        // GET: Serie/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Serie serie = db.Series.Find(id);
            if (serie == null)
            {
                return HttpNotFound();
            }
            return View(serie);
        }

        // POST: Serie/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Serie serie = db.Series.Find(id);
            db.Series.Remove(serie);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NetflixApp/Views/Serie/Create.cshtml
@model NetflixApp.Models.Serie

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
	<h4>Serie</h4>
	<hr />
	@Html.ValidationSummary(true, "", new { @class = "text-danger" })
	<div class="form-group">
		@Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.ReleaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.ReleaseDate, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.Genre, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.Seasons, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.Seasons, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Seasons, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		<div class="col-md-offset-2 col-md-10">
			<input type="submit" value="Create" class="btn btn-default" />
		</div>
	</div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

NetflixApp/Views/Serie/Delete.cshtml
@model NetflixApp.Models.Serie

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Serie</h4>
    <hr />
	<dl class="dl-horizontal">
		<dt>
			@Html.DisplayNameFor(model => model.Title)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Title)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.ReleaseDate)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.ReleaseDate)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.Genre)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Genre)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.Seasons)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Seasons)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.Rating)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Rating)
		</dd>

	</dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

NetflixApp/Views/Serie/Details.cshtml
@model NetflixApp.Models.Serie

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Serie</h4>
    <hr />
	<dl class="dl-horizontal">
		<dt>
			@Html.DisplayNameFor(model => model.Title)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Title)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.ReleaseDate)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.ReleaseDate)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.Genre)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Genre)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.Seasons)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Seasons)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.Rating)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Rating)
		</dd>

	</dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

NetflixApp/Views/Serie/Edit.cshtml
@model NetflixApp.Models.Serie

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
	<h4>Serie</h4>
	<hr />
	@Html.ValidationSummary(true, "", new { @class = "text-danger" })
	@Html.HiddenFor(model => model.ID)

	<div class="form-group">
		@Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.ReleaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.ReleaseDate, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.Genre, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.Seasons, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.Seasons, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Seasons, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		<div class="col-md-offset-2 col-md-10">
			<input type="submit" value="Save" class="btn btn-default" />
		</div>
	</div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

NetflixApp/Views/Serie/Index.cshtml
@model IEnumerable<NetflixApp.Models.Serie>

@{
	ViewBag.Title = "Index";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
	@Html.ActionLink("Create New", "Create")

	@using (Html.BeginForm("Index", "Serie", FormMethod.Get))
	{
		<div>
			Genre: @Html.DropDownList("serieGenre", "All")
			Title: @Html.TextBox("searchString")<br />
			<input type="submit" value="Search" />
		</div>
	}
</p>
<table class="table">
	<tr>
		<th>
			@Html.DisplayNameFor(model => model.Title)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.ReleaseDate)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Genre)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Seasons)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Rating)
		</th>
		<th></th>
	</tr>

@foreach (var item in Model) {
	<tr>
		<td>
			@Html.DisplayFor(modelItem => item.Title)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.ReleaseDate)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.Genre)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.Seasons)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.Rating)
		</td>
		<td>
			@Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
			@Html.ActionLink("Details", "Details", new { id = item.ID }) |
			@Html.ActionLink("Delete", "Delete", new { id = item.ID })
		</td>
	</tr>
}

</table>